# Generated by Django 4.2 on 2024-06-21 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_options_alter_user_table"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ("email",),
                "verbose_name": "пользователя",
                "verbose_name_plural": "пользователи",
            },
        ),
    ]
