# Generated by Django 4.2 on 2024-06-21 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="country",
            field=models.CharField(max_length=40, verbose_name="страна"),
        ),
    ]
