# Generated by Django 4.2 on 2024-06-22 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, unique=True, verbose_name='заголовок')),
                ('slug', models.CharField(max_length=120, verbose_name='слаг')),
                ('content', models.TextField(verbose_name='содержимое')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='blog/images', verbose_name='превью(изображение)')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='дата создания')),
                ('published', models.BooleanField(default=False, verbose_name='признак публикации')),
                ('count_views', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='счетчик просмотров')),
            ],
            options={
                'verbose_name': 'блог',
                'verbose_name_plural': 'блоги',
                'db_table': 'blog',
                'ordering': ('count_views',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='наименование')),
                ('description', models.TextField(blank=True, max_length=255, null=True, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'категорию',
                'verbose_name_plural': 'категории',
                'db_table': 'category',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='наименование')),
                ('description', models.TextField(blank=True, max_length=255, null=True, verbose_name='описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/product_image/', verbose_name='изображение')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='цена')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='количество')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('update_at', models.DateTimeField(auto_now_add=True, verbose_name='дата последнего изменения')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.category', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
                'db_table': 'product',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(blank=True, null=True, verbose_name=' номер версии')),
                ('version_name', models.CharField(max_length=150, verbose_name='название версии')),
                ('current_version', models.BooleanField(default=True, verbose_name='признак текущей версии')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='version', to='catalog.product', verbose_name='продукт')),
            ],
            options={
                'verbose_name': 'версия',
                'verbose_name_plural': 'версии',
                'db_table': 'version',
                'ordering': ('version_name',),
            },
        ),
    ]
