# Generated by Django 5.0.4 on 2024-05-08 03:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manufactured_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 8, 8, 7, 23, 497701), verbose_name='дата производства продукта'),
        ),
    ]
