# Generated by Django 5.0.4 on 2024-05-25 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='заголовок')),
                ('slug', models.CharField(max_length=120, verbose_name='слаг')),
                ('content', models.TextField(verbose_name='содержимое')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='blog/images', verbose_name='превью(изображение)')),
                ('created_at', models.DateField(verbose_name='дата создания')),
                ('published', models.BooleanField(default=False, verbose_name='признак публикации')),
                ('count_views', models.IntegerField(blank=True, default=0, null=True, verbose_name='количество просмотров')),
            ],
            options={
                'verbose_name': 'блог',
                'verbose_name_plural': 'блоги',
                'db_table': 'blog',
                'ordering': ('created_at', 'count_views'),
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/product_image/', verbose_name='изображение'),
        ),
    ]
