# Generated by Django 4.2 on 2024-06-27 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_rename_slug_name_product_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.CharField(max_length=120, unique=True, verbose_name="слаг"),
        ),
    ]
