# Generated by Django 4.2 on 2024-06-22 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'permissions': (('add', 'Добавление'), ('change', 'Изменение'), ('delete', 'Удаление')), 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
    ]
