# Generated by Django 5.0.4 on 2024-05-25 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_blog_count_views'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ('count_views',), 'verbose_name': 'блог', 'verbose_name_plural': 'блоги'},
        ),
    ]
