# Generated by Django 5.0.4 on 2024-06-18 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_alter_blog_created_at_alter_product_create_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="title",
            field=models.CharField(
                max_length=120, unique=True, verbose_name="заголовок"
            ),
        ),
    ]
