# Generated by Django 4.2 on 2024-06-24 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_alter_product_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="published",
            field=models.BooleanField(default=False, verbose_name="признак публикации"),
        ),
    ]
