# Generated by Django 4.2 on 2024-06-25 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_product_published"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ("name",),
                "permissions": (
                    ("change_published", "Изменение статуса публикаии"),
                    ("change_description_product", "Изменение описания продукта"),
                    ("change_category_product", "Изменение категории продукта"),
                ),
                "verbose_name": "продукт",
                "verbose_name_plural": "продукты",
            },
        ),
    ]
